title: Midas Movers, LLC
email: midasmovers@gmail.com
description: Website for Midas Movers, LLC
baseurl: "http://jklmnop.github.io/midasmovers-jekyll"
url: "http://jklmnop.github.io/midasmovers-jekyll"
twitter_username: midasmovers
github_username:  jklmnop
markdown: redcarpet