title: Midas Movers, LLC
slogan: You're Golden!
email: midasmovers@gmail.com
description: Website for Midas Movers, LLC
baseurl: ""
url: ""
logo: /img/logo.png
twitter_username: midasmovers
github_username:  jklmnop
markdown: kramdown