title: Midas Movers, LLC
slogan: The Gold Standard in Moving!
email: midasmovers@gmail.com
description: Website for Midas Movers, LLC
baseurl: "http://jklmnop.github.io/midasmovers-jekyll"
url: "http://jklmnop.github.io/midasmovers-jekyll"
logo: "http://jklmnop.github.io/midasmovers-jekyll/img/logo.png"
twitter_username: midasmovers
github_username:  jklmnop
markdown: kramdown
